// Expected shape of the `additional_data` JSON generated by the n8n
// "company-metadata" webhook for Sales Miner companies. Used to validate
// that the AI-generated payload didn't drop any fields.

export const SALES_MINER_ADDITIONAL_DATA_FIELDS = [
	"country",
	"stock_ticker",
	"canonical_name",
	"company_prompt",
	"validation_instructions",
	"instructions",
	"company_symbols",
	"company_url",
	"corporate_url",
	"career_portal_url",
	"investor_portal_url",
	"reports_url",
	"public_parent_company",
	"allowed_entities",
	"parent_source_search_terms",
	"source_urls",
	"logo_url",
] as const;

export const SALES_MINER_PUBLIC_PARENT_COMPANY_FIELDS = [
	"name",
	"legal_name",
	"is_publicly_listed",
	"relationship_to_target",
	"stock_symbols",
	"isin",
	"wkn",
	"investor_portal_url",
	"reports_url",
	"source_usage_policy",
] as const;

export const SALES_MINER_SOURCE_URLS_FIELDS = [
	"target_customer_site",
	"target_corporate_site",
	"target_newsroom",
	"target_careers",
] as const;

export const SALES_MINER_SOURCE_URLS_PARENT_FIELDS = [
	"parent_investor_relations",
	"parent_results_reports",
	"parent_shares",
] as const;

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Returns dot-path field names missing from the additional data object. */
export function getMissingSalesMinerFields(
	data: Record<string, unknown>,
): string[] {
	const missing: string[] = [];

	for (const field of SALES_MINER_ADDITIONAL_DATA_FIELDS) {
		if (!(field in data)) missing.push(field);
	}

	const parentCompany = data.public_parent_company;
	if (isPlainObject(parentCompany)) {
		for (const field of SALES_MINER_PUBLIC_PARENT_COMPANY_FIELDS) {
			if (!(field in parentCompany)) {
				missing.push(`public_parent_company.${field}`);
			}
		}
	}

	const sourceUrls = data.source_urls;
	if (isPlainObject(sourceUrls)) {
		for (const field of SALES_MINER_SOURCE_URLS_FIELDS) {
			if (!(field in sourceUrls)) {
				missing.push(`source_urls.${field}`);
			}
		}
		if (isPlainObject(parentCompany)) {
			for (const field of SALES_MINER_SOURCE_URLS_PARENT_FIELDS) {
				if (!(field in sourceUrls)) {
					missing.push(`source_urls.${field}`);
				}
			}
		}
	}

	return missing;
}
