"use client";

import { BulbOutlined, DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import {
	App,
	Button,
	Checkbox,
	Collapse,
	DatePicker,
	Form,
	Input,
	InputNumber,
	Modal,
	Segmented,
	Select,
	Space,
	Spin,
	Switch,
	Tag,
	Tooltip,
	Typography,
} from "antd";
import dayjs from "dayjs";
import {
	forwardRef,
	useEffect,
	useImperativeHandle,
	useMemo,
	useRef,
	useState,
} from "react";
import { useSalesMinerCustomersList } from "../../hooks/api/useSalesMinerCustomersService";
import {
	useCreateSMReport,
	useCustomerCompanies,
	useReportStepTemplates,
} from "../../hooks/api/useSalesMinerReportsService";
import JsonEditor from "../deep-dive/json-editor";
import { generateReportSettings } from "../../shared/report-settings-webhook";

const { Text } = Typography;

// Sections whose full structure is generated by AI (based on the customer's
// product model + selected companies) — the user only writes an instruction
// in their own words; nothing is sent for these until Generate has run.
const AI_SETTINGS_SECTIONS: Array<{
	key: string;
	label: string;
	placeholder: string;
}> = [
	{
		key: "commercial_geo_scope",
		label: "Commercial Geo Scope",
		placeholder:
			'Describe the geo scope you want to see in this report (e.g. "US only", "EMEA, exclude UK")…',
	},
	{
		key: "competitive_context",
		label: "Competitive context — optional",
		placeholder:
			"Add known competitors, incumbent providers, partners, exclusions, or positioning instructions. Leave blank to generate automatically.",
	},
	{
		key: "evidence_policy_overrides",
		label: "Evidence policy overrides — optional",
		placeholder:
			"Add stricter evidence rules or source restrictions. Leave blank to use the standard SalesMiner evidence policy.",
	},
];

interface FormValues {
	name: string;
	description?: string;
	customerId: number;
	templateId: number;
	windowFrom: dayjs.Dayjs;
	windowTo: dayjs.Dayjs;
	maxOpportunityCount: number;
	language: string;
	hasHorizon: boolean;
	createProductSignals: boolean;
	useForStatistics: boolean;
}

function parseSettingsJson(value: string): Record<string, unknown> | null {
	try {
		const parsed = value.trim() ? JSON.parse(value) : {};
		if (!parsed || typeof parsed !== "object" || Array.isArray(parsed))
			return null;
		return parsed as Record<string, unknown>;
	} catch {
		return null;
	}
}

function stringifySettings(value: Record<string, unknown>): string {
	return JSON.stringify(value, null, 2);
}

export interface CreateSMReportModalHandle {
	/** Opens the modal, optionally pre-selecting these company ids. */
	open: (initialCompanyIds?: number[]) => void;
}

interface Props {
	onCreated?: (id: number) => void;
	/** When set, the modal is scoped to this customer and the field is locked. */
	customerId?: number;
	/** Hide the built-in "Create Report" trigger button — for when the modal
	 * is opened programmatically via ref instead (see CreateSMReportModalHandle). */
	hideTrigger?: boolean;
}

const CreateSMReportModal = forwardRef<CreateSMReportModalHandle, Props>(
	function CreateSMReportModal(
		{ onCreated, customerId: fixedCustomerId, hideTrigger },
		ref,
	) {
		const [open, setOpen] = useState(false);
		const [form] = Form.useForm<FormValues>();
		const { message } = App.useApp();

		const [selectedCustomerId, setSelectedCustomerId] = useState<number | null>(
			null,
		);
		const [selectedCompanyIds, setSelectedCompanyIds] = useState<number[]>([]);

		const [sectionInstructions, setSectionInstructions] = useState<
			Record<string, string>
		>({});
		const [generatedSettings, setGeneratedSettings] = useState<Record<
			string,
			unknown
		> | null>(null);
		const [settingsMode, setSettingsMode] = useState<"fields" | "json">(
			"fields",
		);
		const [settingsObj, setSettingsObj] = useState<Record<string, unknown>>({});
		const [settingsJson, setSettingsJson] = useState("{}");
		const [newSettingsFieldKey, setNewSettingsFieldKey] = useState("");
		const [isGeneratingSettings, setIsGeneratingSettings] = useState(false);
		const nameManuallyEdited = useRef(false);

		const { data: customersData, isLoading: customersLoading } =
			useSalesMinerCustomersList({
				page: 1,
				limit: 200,
				q: "",
			});
		const { data: templatesData, isLoading: templatesLoading } =
			useReportStepTemplates();
		const { data: companiesData, isLoading: companiesLoading } =
			useCustomerCompanies(selectedCustomerId);
		const { mutateAsync: createReport, isPending } = useCreateSMReport();

		const customers = useMemo(
			() => customersData?.data.items ?? [],
			[customersData],
		);
		const templates = useMemo(() => templatesData?.data ?? [], [templatesData]);
		const companies = companiesData?.data ?? [];

		const handleOpen = (initialCompanyIds?: number[]) => {
			form.resetFields();
			form.setFieldsValue({
				windowFrom: dayjs().subtract(1, "year"),
				windowTo: dayjs().subtract(1, "day"),
				maxOpportunityCount: 15,
				language: "en",
				hasHorizon: false,
				createProductSignals: true,
				useForStatistics: true,
				...(templates[0] ? { templateId: templates[0].id } : {}),
				...(fixedCustomerId != null ? { customerId: fixedCustomerId } : {}),
			});
			setSelectedCustomerId(fixedCustomerId ?? null);
			setSelectedCompanyIds(initialCompanyIds ?? []);
			setSectionInstructions({});
			setGeneratedSettings(null);
			setSettingsMode("fields");
			setSettingsObj({});
			setSettingsJson("{}");
			setNewSettingsFieldKey("");
			nameManuallyEdited.current = false;
			setOpen(true);
		};

		useImperativeHandle(ref, () => ({
			open: (initialCompanyIds) => handleOpen(initialCompanyIds),
		}));

		// Templates may still be loading when the modal is first opened — apply
		// the default (first active template by id) as soon as they arrive.
		useEffect(() => {
			if (!open) return;
			if (templates.length === 0) return;
			if (form.getFieldValue("templateId") != null) return;
			form.setFieldValue("templateId", templates[0]!.id);
		}, [open, templates, form]);

		// Suggest a report name from the customer + template version, e.g.
		// "Klarna Group report July 2026" — customer + current month/year.
		// Skipped once the user has edited the name field manually.
		const customerIdWatched = Form.useWatch("customerId", form);
		useEffect(() => {
			if (!open) return;
			if (nameManuallyEdited.current) return;
			const customer = customers.find(
				(c) => Number(c.id) === customerIdWatched,
			);
			if (!customer) return;
			form.setFieldValue(
				"name",
				`${customer.display_name} report ${dayjs().format("MMMM YYYY")}`,
			);
		}, [open, customerIdWatched, customers, form]);

		// The settings preview/edit panel should always mirror the full settings
		// object that will actually be written to the DB — so keep the report-level
		// fields (which have their own dedicated controls elsewhere on the form)
		// synced into it once a generation has produced settings to show.
		const windowFromWatched = Form.useWatch("windowFrom", form);
		const windowToWatched = Form.useWatch("windowTo", form);
		const maxOpportunityCountWatched = Form.useWatch(
			"maxOpportunityCount",
			form,
		);
		const languageWatched = Form.useWatch("language", form);
		const hasHorizonWatched = Form.useWatch("hasHorizon", form);
		const createProductSignalsWatched = Form.useWatch(
			"createProductSignals",
			form,
		);
		const useForStatisticsWatched = Form.useWatch("useForStatistics", form);
		useEffect(() => {
			if (!generatedSettings) return;
			setSettingsObj((prev) => ({
				...prev,
				customer_id: customerIdWatched,
				window_from: windowFromWatched
					? (windowFromWatched as dayjs.Dayjs).format("YYYY-MM-DD")
					: prev.window_from,
				window_to: windowToWatched
					? (windowToWatched as dayjs.Dayjs).format("YYYY-MM-DD")
					: prev.window_to,
				max_opportunity_count: maxOpportunityCountWatched,
				language: languageWatched,
				has_horizon: hasHorizonWatched,
				create_product_signals: createProductSignalsWatched,
				use_for_statistics: useForStatisticsWatched,
			}));
		}, [
			generatedSettings,
			customerIdWatched,
			windowFromWatched,
			windowToWatched,
			maxOpportunityCountWatched,
			languageWatched,
			hasHorizonWatched,
			createProductSignalsWatched,
			useForStatisticsWatched,
		]);

		const handleCustomerChange = (value: number) => {
			setSelectedCustomerId(value);
			setSelectedCompanyIds([]);
		};

		const handleSelectAll = () => {
			setSelectedCompanyIds(
				companies.filter((c) => c.verified).map((c) => c.companyId),
			);
		};

		const handleDeselectAll = () => {
			setSelectedCompanyIds([]);
		};

		const handleGenerateSettings = async () => {
			if (!selectedCustomerId) {
				message.warning("Select a customer first");
				return;
			}
			if (selectedCompanyIds.length === 0) {
				message.warning("Select at least one account first");
				return;
			}
			setGeneratedSettings(null);
			setSettingsObj({});
			setSettingsJson("{}");
			setSettingsMode("fields");
			setIsGeneratingSettings(true);
			try {
				const userInstructions = Object.fromEntries(
					AI_SETTINGS_SECTIONS.map((section) => {
						const value = sectionInstructions[section.key]?.trim();
						return [section.key, value ? value : null];
					}),
				);
				const generated = await generateReportSettings({
					customerId: selectedCustomerId,
					accountIds: selectedCompanyIds,
					userInstructions,
				});
				const windowFromValue = form.getFieldValue("windowFrom") as
					| dayjs.Dayjs
					| undefined;
				const windowToValue = form.getFieldValue("windowTo") as
					| dayjs.Dayjs
					| undefined;
				const fullSettings: Record<string, unknown> = {
					...generated,
					customer_id: selectedCustomerId,
					window_from: windowFromValue?.format("YYYY-MM-DD"),
					window_to: windowToValue?.format("YYYY-MM-DD"),
					max_opportunity_count: form.getFieldValue("maxOpportunityCount"),
					language: form.getFieldValue("language"),
					has_horizon: form.getFieldValue("hasHorizon"),
					create_product_signals: form.getFieldValue("createProductSignals"),
					use_for_statistics: form.getFieldValue("useForStatistics"),
				};
				setGeneratedSettings(fullSettings);
				setSettingsObj(fullSettings);
				setSettingsJson(stringifySettings(fullSettings));
				setSettingsMode("fields");
			} catch (err) {
				message.error(
					err instanceof Error ? err.message : "Failed to generate settings",
				);
			} finally {
				setIsGeneratingSettings(false);
			}
		};

		const handleSubmit = async (values: FormValues) => {
			let generatedFinal: Record<string, unknown> | null = null;
			if (generatedSettings) {
				if (settingsMode === "json") {
					generatedFinal = parseSettingsJson(settingsJson);
					if (!generatedFinal) {
						message.error("Invalid JSON in generated settings");
						return;
					}
				} else {
					generatedFinal = settingsObj;
				}
			}

			const settings: Record<string, unknown> = {
				...(generatedFinal ?? {}),
				customer_id: values.customerId,
				window_from: values.windowFrom.format("YYYY-MM-DD"),
				window_to: values.windowTo.format("YYYY-MM-DD"),
				max_opportunity_count: values.maxOpportunityCount,
				language: values.language,
				has_horizon: values.hasHorizon,
				create_product_signals: values.createProductSignals,
				use_for_statistics: values.useForStatistics,
			};

			try {
				const result = await createReport({
					name: values.name,
					description: values.description,
					customerId: values.customerId,
					templateId: values.templateId,
					windowFrom: values.windowFrom.format("YYYY-MM-DD"),
					windowTo: values.windowTo.format("YYYY-MM-DD"),
					maxOpportunityCount: values.maxOpportunityCount,
					companyIds: selectedCompanyIds,
					settings,
				});
				message.success(`Report "${result.data.name}" created`);
				setOpen(false);
				onCreated?.(result.data.id);
			} catch {
				message.error("Failed to create report");
			}
		};

		const generatedSettingsPanel = (
			<>
				<div
					style={{
						display: "flex",
						justifyContent: "flex-end",
						marginBottom: 8,
					}}
				>
					<Segmented<"fields" | "json">
						size="small"
						value={settingsMode}
						options={[
							{ label: "Fields", value: "fields" },
							{ label: "JSON", value: "json" },
						]}
						onChange={(val) => {
							if (val === "fields") {
								const parsed = parseSettingsJson(settingsJson);
								if (!parsed) {
									message.error("Fix invalid JSON before switching to fields");
									return;
								}
								setSettingsObj(parsed);
							} else {
								setSettingsJson(stringifySettings(settingsObj));
							}
							setSettingsMode(val);
						}}
					/>
				</div>

				{settingsMode === "json" ? (
					<JsonEditor
						value={settingsJson}
						onChange={setSettingsJson}
						height="480px"
					/>
				) : (
					<Space
						direction="vertical"
						size="middle"
						style={{
							width: "100%",
							maxHeight: 480,
							overflowY: "auto",
							border: "1px solid #303030",
							borderRadius: 6,
							padding: 12,
						}}
					>
						{Object.entries(settingsObj).map(([key, value]) => {
							const fieldLabel = (
								<div
									style={{
										display: "flex",
										justifyContent: "space-between",
										alignItems: "center",
										marginBottom: 4,
									}}
								>
									<Text style={{ color: "#8c8c8c", fontSize: 12 }}>{key}</Text>
									<Button
										type="text"
										size="small"
										icon={<DeleteOutlined />}
										style={{ color: "#595959" }}
										onClick={() =>
											setSettingsObj((prev) => {
												const next = { ...prev };
												delete next[key];
												return next;
											})
										}
									/>
								</div>
							);

							if (typeof value === "boolean") {
								return (
									<div key={key}>
										{fieldLabel}
										<Switch
											checked={value}
											onChange={(checked) =>
												setSettingsObj((prev) => ({ ...prev, [key]: checked }))
											}
										/>
									</div>
								);
							}

							if (typeof value === "number") {
								return (
									<div key={key}>
										{fieldLabel}
										<InputNumber
											value={value}
											onChange={(next) =>
												setSettingsObj((prev) => ({
													...prev,
													[key]: next ?? null,
												}))
											}
											style={{ width: "100%" }}
										/>
									</div>
								);
							}

							if (typeof value === "string" || value === null) {
								return (
									<div key={key}>
										{fieldLabel}
										<Input.TextArea
											autoSize={{ minRows: 1, maxRows: 8 }}
											value={value ?? ""}
											onChange={(e) =>
												setSettingsObj((prev) => ({
													...prev,
													[key]: e.target.value,
												}))
											}
										/>
									</div>
								);
							}

							return (
								<div key={key}>
									{fieldLabel}
									<Input.TextArea
										autoSize={{ minRows: 2, maxRows: 12 }}
										value={JSON.stringify(value, null, 2)}
										onChange={(e) => {
											try {
												setSettingsObj((prev) => ({
													...prev,
													[key]: JSON.parse(e.target.value),
												}));
											} catch {
												setSettingsObj((prev) => ({
													...prev,
													[key]: e.target.value,
												}));
											}
										}}
									/>
								</div>
							);
						})}

						<div style={{ display: "flex", gap: 8 }}>
							<Input
								value={newSettingsFieldKey}
								onChange={(e) => setNewSettingsFieldKey(e.target.value)}
								placeholder="New field name"
								onPressEnter={() => {
									const k = newSettingsFieldKey.trim();
									if (!k) return;
									if (k in settingsObj) {
										message.warning("Field already exists");
										return;
									}
									setSettingsObj((prev) => ({ ...prev, [k]: "" }));
									setNewSettingsFieldKey("");
								}}
							/>
							<Button
								icon={<PlusOutlined />}
								onClick={() => {
									const k = newSettingsFieldKey.trim();
									if (!k) return;
									if (k in settingsObj) {
										message.warning("Field already exists");
										return;
									}
									setSettingsObj((prev) => ({ ...prev, [k]: "" }));
									setNewSettingsFieldKey("");
								}}
							>
								Add field
							</Button>
						</div>
					</Space>
				)}
			</>
		);

		return (
			<>
				{!hideTrigger && (
					<Button
						type="primary"
						icon={<PlusOutlined />}
						onClick={() => handleOpen()}
					>
						Create Report
					</Button>
				)}

				<Modal
					title="Create Sales Miner Report"
					open={open}
					onCancel={() => setOpen(false)}
					footer={null}
					width="80vw"
					style={{ top: "10vh" }}
					styles={{ body: { maxHeight: "80vh", overflowY: "auto" } }}
					destroyOnClose
				>
					<Form
						form={form}
						layout="vertical"
						onFinish={(v) => {
							void handleSubmit(v);
						}}
						style={{ marginTop: 16 }}
					>
						<div style={{ display: "flex", gap: 24, alignItems: "flex-start" }}>
							{/* ── Companies ── */}
							<div style={{ flex: "0 0 260px" }}>
								<div
									style={{
										marginBottom: 8,
										display: "flex",
										alignItems: "center",
										justifyContent: "space-between",
									}}
								>
									<Text style={{ fontSize: 13, color: "#d9d9d9" }}>
										Companies
									</Text>
									{companies.length > 0 && (
										<Text type="secondary" style={{ fontSize: 12 }}>
											{selectedCompanyIds.length} / {companies.length} selected
										</Text>
									)}
								</div>

								{!selectedCustomerId ? (
									<div
										style={{
											border: "1px solid #303030",
											borderRadius: 6,
											padding: "12px 16px",
										}}
									>
										<Text type="secondary" style={{ fontSize: 12 }}>
											Select a customer to see available companies
										</Text>
									</div>
								) : companiesLoading ? (
									<div
										style={{
											textAlign: "center",
											padding: "24px 0",
											border: "1px solid #303030",
											borderRadius: 6,
										}}
									>
										<Spin size="small" />
									</div>
								) : companies.length === 0 ? (
									<div
										style={{
											border: "1px solid #303030",
											borderRadius: 6,
											padding: "12px 16px",
										}}
									>
										<Text type="secondary" style={{ fontSize: 12 }}>
											No companies found for this customer
										</Text>
									</div>
								) : (
									<>
										<div style={{ display: "flex", gap: 8, marginBottom: 8 }}>
											<Button size="small" onClick={handleSelectAll}>
												Select all
											</Button>
											<Button size="small" onClick={handleDeselectAll}>
												Deselect all
											</Button>
										</div>
										<div
											style={{
												maxHeight: 480,
												overflowY: "auto",
												border: "1px solid #303030",
												borderRadius: 6,
												padding: "4px 0",
											}}
										>
											{companies.map((c) => (
												<div
													key={c.companyId}
													style={{
														padding: "4px 12px",
														cursor: c.verified ? "pointer" : "not-allowed",
														opacity: c.verified ? 1 : 0.5,
													}}
													onClick={() => {
														if (!c.verified) return;
														setSelectedCompanyIds((prev) =>
															prev.includes(c.companyId)
																? prev.filter((id) => id !== c.companyId)
																: [...prev, c.companyId],
														);
													}}
												>
													<Checkbox
														checked={selectedCompanyIds.includes(c.companyId)}
														disabled={!c.verified}
														style={{ pointerEvents: "none" }}
													>
														<Text style={{ fontSize: 13 }}>
															{c.name}{" "}
															<Text type="secondary" style={{ fontSize: 12 }}>
																#{c.companyId}
															</Text>
															{!c.verified && (
																<Tooltip title="Unverified companies can't be added to a report">
																	<Tag
																		color="warning"
																		style={{ marginLeft: 6, fontSize: 11 }}
																	>
																		unverified
																	</Tag>
																</Tooltip>
															)}
														</Text>
													</Checkbox>
												</div>
											))}
										</div>
									</>
								)}
							</div>

							{/* ── Manual fields ── */}
							<div style={{ flex: "0 0 320px" }}>
								<Form.Item
									name="name"
									label="Report Name"
									rules={[{ required: true, message: "Required" }]}
								>
									<Input
										placeholder="Report name"
										onChange={() => {
											nameManuallyEdited.current = true;
										}}
									/>
								</Form.Item>

								<Form.Item name="description" label="Description">
									<Input.TextArea rows={2} placeholder="Optional description" />
								</Form.Item>

								<Form.Item
									name="customerId"
									label="Customer"
									rules={[{ required: true, message: "Required" }]}
								>
									<Select
										placeholder="Select customer"
										loading={customersLoading}
										disabled={fixedCustomerId != null}
										showSearch
										optionFilterProp="label"
										options={customers.map((c) => ({
											value: Number(c.id),
											label: c.display_name,
										}))}
										onChange={handleCustomerChange}
									/>
								</Form.Item>

								<Form.Item
									name="templateId"
									label="Orchestrator Steps"
									rules={[{ required: true, message: "Required" }]}
								>
									<Select
										placeholder="Select template"
										loading={templatesLoading}
										options={templates.map((t) => ({
											value: t.id,
											label: `${t.name} (${t.code})`,
										}))}
									/>
								</Form.Item>

								<Form.Item
									name="windowFrom"
									label="Window From"
									rules={[{ required: true, message: "Required" }]}
								>
									<DatePicker style={{ width: "100%" }} allowClear={false} />
								</Form.Item>

								<Form.Item
									name="windowTo"
									label="Window To"
									rules={[{ required: true, message: "Required" }]}
								>
									<DatePicker style={{ width: "100%" }} allowClear={false} />
								</Form.Item>

								<Form.Item
									name="maxOpportunityCount"
									label="Max Opportunity Count"
									rules={[{ required: true, message: "Required" }]}
								>
									<InputNumber min={1} max={100} style={{ width: "100%" }} />
								</Form.Item>

								<Form.Item
									name="language"
									label="Language"
									style={{ marginBottom: 8 }}
								>
									<Select
										style={{ width: 140 }}
										options={[
											{ value: "en", label: "English" },
											{ value: "de", label: "German" },
										]}
									/>
								</Form.Item>

								<Space size="middle" wrap style={{ marginBottom: 0 }}>
									<Form.Item name="hasHorizon" valuePropName="checked" noStyle>
										<Checkbox>Has horizon</Checkbox>
									</Form.Item>
									<Form.Item
										name="createProductSignals"
										valuePropName="checked"
										noStyle
									>
										<Checkbox>Create product signals</Checkbox>
									</Form.Item>
									<Form.Item
										name="useForStatistics"
										valuePropName="checked"
										noStyle
									>
										<Checkbox>Use for statistics</Checkbox>
									</Form.Item>
								</Space>
							</div>

							{/* ── AI-generated settings ── */}
							<div style={{ flex: 1, minWidth: 0 }}>
								<div
									style={{
										display: "flex",
										justifyContent: "space-between",
										alignItems: "center",
										marginBottom: 8,
									}}
								>
									<Text style={{ fontSize: 13, color: "#d9d9d9" }}>
										Report Settings
									</Text>
									<Tooltip
										title={
											selectedCompanyIds.length === 0
												? "Select at least one account first"
												: undefined
										}
									>
										<span>
											<Button
												size="small"
												type="primary"
												icon={<BulbOutlined />}
												loading={isGeneratingSettings}
												disabled={selectedCompanyIds.length === 0}
												onClick={() => {
													handleGenerateSettings().catch((err) => {
														console.error(
															"Generate report settings failed",
															err,
														);
													});
												}}
											>
												Generate
											</Button>
										</span>
									</Tooltip>
								</div>

								<Text
									type="secondary"
									style={{ fontSize: 12, display: "block", marginBottom: 12 }}
								>
									Write a short instruction for each section below — AI will use
									it, together with the customer&apos;s product model, to
									generate the full settings.
								</Text>

								<Space
									direction="vertical"
									size="small"
									style={{ width: "100%" }}
								>
									{AI_SETTINGS_SECTIONS.map((section) => (
										<div key={section.key}>
											<Text
												style={{
													fontSize: 12,
													color: "#8c8c8c",
													display: "block",
													marginBottom: 2,
												}}
											>
												{section.label}
											</Text>
											<Input.TextArea
												autoSize={{ minRows: 1, maxRows: 2 }}
												placeholder={section.placeholder}
												value={sectionInstructions[section.key] ?? ""}
												onChange={(e) =>
													setSectionInstructions((prev) => ({
														...prev,
														[section.key]: e.target.value,
													}))
												}
											/>
										</div>
									))}
								</Space>

								{generatedSettings && (
									<Collapse
										style={{ marginTop: 16 }}
										defaultActiveKey={["generated"]}
										items={[
											{
												key: "generated",
												label: "Generated settings — review / edit",
												children: generatedSettingsPanel,
											},
										]}
									/>
								)}
							</div>
						</div>

						<div style={{ textAlign: "right", marginTop: 16 }}>
							<Button onClick={() => setOpen(false)} style={{ marginRight: 8 }}>
								Cancel
							</Button>
							<Button type="primary" htmlType="submit" loading={isPending}>
								Create
							</Button>
						</div>
					</Form>
				</Modal>
			</>
		);
	},
);

export default CreateSMReportModal;
