'use client';

import { CheckCircleOutlined, DownloadOutlined, DownOutlined, FilePdfOutlined, FileTextOutlined, LinkOutlined, ToolOutlined, TrophyOutlined } from '@ant-design/icons';
import { Button, Card, Collapse, Layout, message, Space, Typography } from 'antd';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { AnalysisContent, AnalysisData, exportAnalysisReportDocx } from '../../lib/docx-export';
import { markdownToPdf } from '../../lib/pdf.export';
import Sidebar from '../ui/sidebar';

const { Title, Text } = Typography;
const { Content } = Layout;
const { Panel } = Collapse;

interface AnalyzeQuizData {
  companyName: string;
  businessLine: string;
  country: string;
  useCase: string;
  timeline: string;
  additionalInformation?: string;
}

interface ExtendedAnalyzeResultProps {
  quizData: AnalyzeQuizData;
  summary?: string;
  improvementLeverages?: string;
  headToHead?: string;
  sources?: string;
  onReset: () => void;
}

export default function ExtendedAnalyzeResult({ 
  quizData, 
  summary, 
  improvementLeverages, 
  headToHead, 
  sources, 
  onReset 
}: ExtendedAnalyzeResultProps) {
  const [activePanels, setActivePanels] = useState<string[]>(['summary']);

  const handlePanelChange = (key: string | string[]) => {
    setActivePanels(Array.isArray(key) ? key : [key]);
  };

  const generateMarkdownReport = (): string => {
    const reportDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    let markdown = `# Analysis Report\n\n`;
    markdown += `**Generated on:** ${reportDate}\n\n`;
    
    // Analysis Parameters
    markdown += `## Analysis Parameters\n\n`;
    markdown += `| Parameter | Value |\n`;
    markdown += `|-----------|-------|\n`;
    markdown += `| Company | ${quizData.companyName} |\n`;
    markdown += `| Business Line | ${quizData.businessLine} |\n`;
    markdown += `| Country | ${quizData.country} |\n`;
    markdown += `| Use Case | ${quizData.useCase} |\n`;
    markdown += `| Timeline | ${quizData.timeline} |\n`;
    if (quizData.additionalInformation) {
      markdown += `| Additional Information | ${quizData.additionalInformation} |\n`;
    }
    markdown += `\n`;

    // Executive Summary
    if (summary && summary.trim()) {
      markdown += `## Executive Summary\n\n`;
      markdown += `${summary}\n\n`;
    }

    // Head to Head Analysis
    if (headToHead && headToHead.trim()) {
      markdown += `## Head to Head Analysis\n\n`;
      markdown += `${headToHead}\n\n`;
    }

    // Improvement Leverages
    if (improvementLeverages && improvementLeverages.trim()) {
      markdown += `## Improvement Leverages\n\n`;
      markdown += `${improvementLeverages}\n\n`;
    }

    // Sources & References
    if (sources && sources.trim()) {
      markdown += `## Sources & References\n\n`;
      markdown += `${sources}\n\n`;
    }

    markdown += `---\n`;
    markdown += `*Report generated by Vitelis Analysis System*\n`;

    return markdown;
  };

  const handleExportToDocx = async () => {
    try {
      const analysisData: AnalysisData = {
        companyName: quizData.companyName,
        businessLine: quizData.businessLine,
        country: quizData.country,
        useCase: quizData.useCase,
        timeline: quizData.timeline,
        additionalInformation: quizData.additionalInformation
      };

      const analysisContent: AnalysisContent = {
        summary,
        improvementLeverages,
        headToHead,
        sources
      };

      await exportAnalysisReportDocx(analysisData, analysisContent, 'Bizminer Analysis');
      message.success('Analysis report exported successfully!');
    } catch (error) {
      console.error('Export error:', error);
      message.error('Failed to export report. Please try again.');
    }
  };

  const handleExportToPdf = async () => {
    try {
      const markdownReport = generateMarkdownReport();
      const filename = `${quizData.companyName.replace(/\s+/g, '_')}_Bizminer_Analysis_${new Date().toISOString().split('T')[0]}.pdf`;

     
      await markdownToPdf(markdownReport, {
        filename,
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        format: 'a4',
        orientation: 'portrait',
        margin: 15,
        scale: 1.25,
      });
     

      message.success('PDF report exported successfully!');
    } catch (error) {
      console.error('PDF export error:', error);
      message.error('Failed to export PDF report. Please try again.');
    }
  };

  const renderMarkdownContent = (content: string | undefined, fallbackText: string) => {
    if (!content || content.trim() === '') {
      return (
        <div style={{ 
          color: '#8c8c8c', 
          fontStyle: 'italic',
          textAlign: 'center',
          padding: '20px'
        }}>
          {fallbackText}
        </div>
      );
    }

    return (
      <div style={{ 
        color: '#d9d9d9',
        fontSize: '14px',
        lineHeight: '1.6'
      }}>
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({children}) => <h1 style={{color: '#58bfce', fontSize: '20px', marginBottom: '12px', marginTop: '16px'}}>{children}</h1>,
            h2: ({children}) => <h2 style={{color: '#58bfce', fontSize: '18px', marginBottom: '10px', marginTop: '14px'}}>{children}</h2>,
            h3: ({children}) => <h3 style={{color: '#58bfce', fontSize: '16px', marginBottom: '8px', marginTop: '12px'}}>{children}</h3>,
            h4: ({children}) => <h4 style={{color: '#58bfce', fontSize: '14px', marginBottom: '6px', marginTop: '10px'}}>{children}</h4>,
            p: ({children}) => <p style={{marginBottom: '12px'}}>{children}</p>,
            strong: ({children}) => <strong style={{color: '#ffffff'}}>{children}</strong>,
            a: ({children, href}) => (
              <a 
                href={href} 
                target="_blank" 
                rel="noopener noreferrer"
                style={{
                  color: '#1890ff',
                  textDecoration: 'underline',
                  textDecorationColor: '#1890ff',
                  textDecorationThickness: '1px',
                  textUnderlineOffset: '2px'
                }}
              >
                {children}
              </a>
            ),
            table: ({children}) => (
              <div style={{ overflowX: 'auto', marginBottom: '16px' }}>
                <table style={{
                  width: '100%', 
                  borderCollapse: 'collapse', 
                  marginBottom: '16px',
                  minWidth: '600px'
                }}>
                  {children}
                </table>
              </div>
            ),
            th: ({children}) => (
              <th style={{
                border: '1px solid #434343', 
                padding: '12px 8px', 
                textAlign: 'left', 
                backgroundColor: '#1f1f1f', 
                color: '#58bfce',
                fontWeight: 'bold',
                fontSize: '14px'
              }}>
                {children}
              </th>
            ),
            td: ({children}) => (
              <td style={{
                border: '1px solid #434343', 
                padding: '12px 8px', 
                color: '#d9d9d9',
                fontSize: '14px',
                verticalAlign: 'top'
              }}>
                {children}
              </td>
            ),
            ul: ({children}) => <ul style={{marginBottom: '12px', paddingLeft: '20px'}}>{children}</ul>,
            ol: ({children}) => <ol style={{marginBottom: '12px', paddingLeft: '20px'}}>{children}</ol>,
            li: ({children}) => <li style={{marginBottom: '4px'}}>{children}</li>,
            blockquote: ({children}) => <blockquote style={{borderLeft: '4px solid #58bfce', paddingLeft: '16px', margin: '16px 0', fontStyle: 'italic', color: '#8c8c8c'}}>{children}</blockquote>,
            code: ({children}) => <code style={{backgroundColor: '#1f1f1f', padding: '2px 6px', borderRadius: '4px', fontFamily: 'monospace'}}>{children}</code>,
            pre: ({children}) => <pre style={{backgroundColor: '#1f1f1f', padding: '16px', borderRadius: '8px', overflow: 'auto', marginBottom: '16px'}}>{children}</pre>
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
    );
  };

  return (
    <Layout style={{ minHeight: '100vh', background: '#141414' }}>
      <Sidebar />
      <Layout style={{ marginLeft: 280, background: '#141414' }}>
        <Content style={{ 
          padding: '24px',
          background: '#141414',
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column'
        }}>
          <div style={{ width: '100%' }}>
            <Card 
              style={{ 
                background: '#1f1f1f', 
                border: '1px solid #303030',
                borderRadius: '12px'
              }}
            >
              {/* Header */}
              <div style={{ textAlign: 'center', marginBottom: '32px' }}>
                <Title level={2} style={{ color: '#58bfce', marginBottom: '8px' }}>
                  Analysis Report
                </Title>
                <Text style={{ color: '#8c8c8c' }}>
                  Comprehensive analysis with detailed insights
                </Text>
              </div>

              {/* Quiz Data Summary */}
              <Card
                style={{
                  background: '#262626',
                  border: '1px solid #434343',
                  borderRadius: '8px',
                  marginBottom: '32px'
                }}
                styles={{ body: { padding: '20px' } }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px', padding: 'relative' }}>
                  <Title level={4} style={{ color: '#58bfce', margin: 0 }}>
                    Analysis Parameters
                  </Title>
                  <div style={{ display: 'flex', alignItems: 'center', position: 'absolute', right: '65px', top: '75px' }}>
                    <CheckCircleOutlined style={{ color: '#52c41a', marginRight: '12px', fontSize: '32px' }} />
                    <span style={{ color: '#52c41a', fontSize: '24px', fontWeight: '600' }}>Sources verified</span>
                  </div>
                </div>
                <div style={{ color: '#d9d9d9' }}>
                  <p><strong>Company:</strong> {quizData.companyName}</p>
                  <p><strong>Business Line:</strong> {quizData.businessLine}</p>
                  <p><strong>Country:</strong> {quizData.country}</p>
                  <p><strong>Use Case:</strong> {quizData.useCase}</p>
                  <p><strong>Timeline:</strong> {quizData.timeline}</p>
                  {quizData.additionalInformation && (
                    <p><strong>Additional Information:</strong> {quizData.additionalInformation}</p>
                  )}
                </div>
              </Card>

              {/* Collapsible Analysis Sections */}
              <Card
                style={{
                  background: '#262626',
                  border: '1px solid #434343',
                  borderRadius: '8px',
                  marginBottom: '32px'
                }}
                styles={{ body: { padding: '0' } }}
              >
                <Collapse
                  activeKey={activePanels}
                  onChange={handlePanelChange}
                  expandIcon={({ isActive }) => (
                    <DownOutlined 
                      style={{ 
                        color: '#58bfce', 
                        fontSize: '16px',
                        transform: isActive ? 'rotate(180deg)' : 'rotate(0deg)',
                        transition: 'transform 0.3s ease'
                      }} 
                    />
                  )}
                  style={{
                    background: 'transparent',
                    border: 'none'
                  }}
                >
                  {/* Summary Section */}
                  <Panel 
                    header={
                      <div style={{ display: 'flex', alignItems: 'center' }}>
                        <FileTextOutlined style={{ color: '#58bfce', marginRight: '12px', fontSize: '18px' }} />
                        <Title level={4} style={{ color: '#58bfce', margin: 0 }}>
                          Executive Summary
                        </Title>
                      </div>
                    }
                    key="summary"
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      borderRadius: '8px',
                      marginBottom: '8px'
                    }}
                  >
                    <div style={{ padding: '24px' }}>
                      {renderMarkdownContent(summary, 'No summary available yet. Please wait for the analysis to complete.')}
                    </div>
                  </Panel>

                  {/* Head to Head Section */}
                  <Panel 
                    header={
                      <div style={{ display: 'flex', alignItems: 'center' }}>
                        <TrophyOutlined style={{ color: '#58bfce', marginRight: '12px', fontSize: '18px' }} />
                        <Title level={4} style={{ color: '#58bfce', margin: 0 }}>
                          Head to Head Analysis
                        </Title>
                      </div>
                    }
                    key="headToHead"
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      borderRadius: '8px',
                      marginBottom: '8px'
                    }}
                  >
                    <div style={{ padding: '24px' }}>
                      {renderMarkdownContent(headToHead, 'No head-to-head analysis available yet. Please wait for the analysis to complete.')}
                    </div>
                  </Panel>

                  {/* Sources Section */}
                  <Panel 
                    header={
                      <div style={{ display: 'flex', alignItems: 'center' }}>
                        <LinkOutlined style={{ color: '#58bfce', marginRight: '12px', fontSize: '18px' }} />
                        <Title level={4} style={{ color: '#58bfce', margin: 0 }}>
                          Sources & References
                        </Title>
                      </div>
                    }
                    key="sources"
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      borderRadius: '8px',
                      marginBottom: '8px'
                    }}
                  >
                    <div style={{ padding: '24px' }}>
                      {renderMarkdownContent(sources, 'No sources available yet. Please wait for the analysis to complete.')}
                    </div>
                  </Panel>

                  {/* Improvement Leverages Section */}
                  <Panel 
                    header={
                      <div style={{ display: 'flex', alignItems: 'center' }}>
                        <ToolOutlined style={{ color: '#58bfce', marginRight: '12px', fontSize: '18px' }} />
                        <Title level={4} style={{ color: '#58bfce', margin: 0 }}>
                          Improvement Leverages
                        </Title>
                      </div>
                    }
                    key="improvementLeverages"
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      borderRadius: '8px',
                      marginBottom: '8px'
                    }}
                  >
                    <div style={{ padding: '24px' }}>
                      {renderMarkdownContent(improvementLeverages, 'No improvement leverages available yet. Please wait for the analysis to complete.')}
                    </div>
                  </Panel>
                </Collapse>
              </Card>

              {/* Action Buttons */}
              <div style={{ textAlign: 'center' }}>
                <Space>
                  <Button
                    size="large"
                    icon={<DownloadOutlined />}
                    onClick={handleExportToDocx}
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      color: '#d9d9d9',
                      borderRadius: '8px',
                      height: '48px',
                      padding: '0 24px',
                      transition: 'all 0.3s ease'
                    }}
                    className="custom-button"
                  >
                    Export to DOCX
                  </Button>
                  <Button
                    size="large"
                    icon={<FilePdfOutlined />}
                    onClick={handleExportToPdf}
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      color: '#d9d9d9',
                      borderRadius: '8px',
                      height: '48px',
                      padding: '0 24px',
                      transition: 'all 0.3s ease'
                    }}
                    className="custom-button"
                  >
                    Export to PDF
                  </Button>
                  <Button
                    size="large"
                    onClick={onReset}
                    style={{
                      background: '#1f1f1f',
                      border: '1px solid #434343',
                      color: '#d9d9d9',
                      borderRadius: '8px',
                      height: '48px',
                      padding: '0 24px',
                      transition: 'all 0.3s ease'
                    }}
                    className="custom-button"
                  >
                    Start New Analysis
                  </Button>
                </Space>
              </div>
            </Card>
          </div>
        </Content>
      </Layout>
    </Layout>
  );
}
