import type { ReactNode } from "react";

export const metadata = {
  title: "Example",
  description: "Generated by create next app",
};

export default function ExampleLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
